
export const babySizeComparisons = {
  1: { item: "Poppy seed", image: "🌱" },
  2: { item: "Sesame seed", image: "🌱" },
  3: { item: "Blueberry", image: "🫐" },
  4: { item: "Kidney bean", image: "🫘" },
  5: { item: "Grape", image: "🍇" },
  6: { item: "Pea", image: "🌱" },
  7: { item: "Blueberry", image: "🫐" },
  8: { item: "Kidney bean", image: "🫘" },
  9: { item: "Grape", image: "🍇" },
  10: { item: "Kumquat", image: "🍊" },
  11: { item: "Fig", image: "🥭" },
  12: { item: "Lime", image: "🍋" },
  13: { item: "Lemon", image: "🍋" },
  14: { item: "Navel orange", image: "🍊" },
  15: { item: "Apple", image: "🍎" },
  16: { item: "Avocado", image: "🥑" },
  17: { item: "Pomegranate", image: "🫒" },
  18: { item: "Bell pepper", image: "🫑" },
  19: { item: "Mango", image: "🥭" },
  20: { item: "Banana", image: "🍌" },
  21: { item: "Carrot", image: "🥕" },
  22: { item: "Corn on the cob", image: "🌽" },
  23: { item: "Grapefruit", image: "🍊" },
  24: { item: "Ear of corn", image: "🌽" },
  25: { item: "Cauliflower", image: "🥦" },
  26: { item: "Kale", image: "🥬" },
  27: { item: "Cauliflower", image: "🥦" },
  28: { item: "Eggplant", image: "🍆" },
  29: { item: "Butternut squash", image: "🎃" },
  30: { item: "Cabbage", image: "🥬" },
  31: { item: "Coconut", image: "🥥" },
  32: { item: "Squash", image: "🎃" },
  33: { item: "Pineapple", image: "🍍" },
  34: { item: "Cantaloupe", image: "🍈" },
  35: { item: "Honeydew melon", image: "🍈" },
  36: { item: "Romaine lettuce", image: "🥬" },
  37: { item: "Swiss chard", image: "🥬" },
  38: { item: "Pumpkin", image: "🎃" },
  39: { item: "Watermelon", image: "🍉" },
  40: { item: "Small pumpkin", image: "🎃" }
};
